spring:
  datasource:
    url: jdbc:mysql://localhost:3306/content_center
    username: root
    password: root
    # >= 6.x: com.mysql.cj.jdbc.Driver
    # <= 5.x: com.mysql.jdbc.Driver
    driver-class-name: com.mysql.jdbc.Driver
  cloud:
    nacos:
      discovery:
        #指定nacous server地址
        server-addr: localhost:8848
  application:
    name: conter-center
server:
  port: 8081
management:
  endpoints:
    web:
    exposure:
    include: '*'
  endpoint:
    health:
    show-details: always
ribbon:
  eager-load:
    enabled: false
    clients: user-center